[package]
name = "nixbom"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
chrono = "0.4"
